FROM node:21

WORKDIR /usr/scr/app

COPY . .

RUN npm install

RUN npm run build

RUN rm -rf ./src

EXPOSE 5001

#npm run start:prod will start the server in production mode.
CMD ["npm", "run", "start:prod"]